### ISSUE TITLE
Differentiate rcMinPrice from rcInitialPrice

### ISSUE THREAD

**Issue by ceilican** [DjedAlliance/Djed-Solidity#12]
In this file (https://github.com/DjedAlliance/Djed-Solidity/blob/main/src/Djed.sol), we can see that the contract takes an `rcMinPrice` as a parameter and uses it both as an initial price in line 213 and as a minimum price in line 214.  We should modify the contract so that it takes two arguments (`rcMinPrice` and `rcInitialPrice`) and uses them accordingly. 

We should also modify test files and deployment scripts, so that they are compatible with the new  contract.

**Comment by yogesh0509** [comment]
What should be the `RESERVE_COIN_WHOLE_INITIAL_PRICE` in the [Utilities.sol](https://github.com/DjedAlliance/Djed-Solidity/blob/main/src/test/Utilities.sol).

**Comment by ceilican** [comment]
Let's make it `1e20`.
